title:        PSD2
description:  Research into PSD2 banking.
url:          https://psd2.apievangelist.com
raw_url: https://raw.githubusercontent.com/api-evangelist/psd2/master/_data/api-commons/

version:      1.1.1

author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown
permalink:    pretty
pygments:     true
highlighter:  rouge

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

categories_path : /categories.html
tags_path : /tags.html

production_url : https://apievangelist.com

image : http://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png
imagesecure : https://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png

github_user: api-evangelist
github_repo: public-data-api-management

footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60
